services:
  - type: web
    name: lostandfound-backend
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/LostAndFound-0.0.1-SNAPSHOT.jar
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
